simranlotey/Hacktoberfest

Sorting_Algorithms/Python/bubbleSort.py, Sorting_Algorithms/Python/mergeSort.py
=> merge sort python implementation added

Searching_Algorithms/Python/linearSearch.py
=> Added Linear Search file

Javascript/BasicPyramid.js
=> added code of pyramid

Python/pal.py
* This code can check wether the number which is given as a input by the person is palindrome or not
=> Pyhton: Palindrome Number

Python/diamondPattern.py
Issue #11 
Added Diamond Pattern in Python.
=> Added Diamond Pattern in Python

added code of bubble sort in Javascript
=> Create added code of bubble sort in Javascript

Searching_Algorithms/Python/binary_search.py, Searching_Algorithms/Python/interpolation_search.py
* Create binary_search.py
* Create interpolation_search.py
=> Added binary_search and interpolation_search

C++/BinaryToDecimal.cpp
I have added the code.If there any changes let me know
Ticket#30
=> Added Binary to decimal code

NumberBase_Converter.js
Created a file. User should enter the number and base of the number. The result will be the binary, hex, dec, oct format of that number. Please mark my files as viewed and review my PR, it will help me  a lot. [because I am on a competition and it counts as PR reviewed]. Thank you.
=> add: number base converter

program_quadratic_eqn.java
Issue #49 I've added program to solve quadratic equations of the form ax^2 + bx + c = 0 in java.
=> Issue #49 Program for quadratic equation is done in java.

Python/bank.py
=> python script for simple bank system simulation

Weather_forecasting.py
Issue No.: #70 
Text Based Weather Forecast
=> Weather_Forecasting 

Python/romanToArabic.py
This PR addresses issue [66](https://github.com/simranlotey/programs/issues/66) which is about adding a Roman numeral to Arabic numeral conversion function to the project. I've implemented the roman_to_arabic function that can convert Roman numerals to Arabic numerals with an explanation of the code. This functionality can be useful for various applications within the project. Please review and merge this PR to incorporate this feature.
`python romanToArabic.py -i XXI`
`Arabic number: 21`
=> Roman Numeral to Arabic Numeral Conversion

todojs.html, todojs.js
#29 I create an todo list with the help of JS and HTML.I am not use to style it.....so its just an normal todo list with delete option.
=> add branch

Python/analyze_string.py
Fixes #35 
- python program to counts vowels, consonants, numbers and special characters
=> python program to analyze a string

Python/simulation.py
created a python program to simulate Conway's law of live using pygame
=> python simulation

Celsius_to_Fahrenheit.java
Issue #27  I've added program to convert a temperature from Celsius to Fahrenheit in Java.
=> Issue #27 Program to convert temperature is added.

Sorting_Algorithms/Python/insertionSort.py
Coded for the most efficient way to perform the Insertion Sort technique.
=> Insertion Sort Algorithm

convert_units.js
=> convert units using js

Javascript/fibonacci_prime_numbers.js
=> add: fibonacci prime numbers in js

InversionCount.java
Hi @simranlotey , I have added the solution of the Count Inversion Problem in an Array. Please merge this PR.
=> Count Inversion in an Array

program_median.java
Issue #54  I've added a Java program to find the median of a list of numbers
=> A program to find median is added.

Build a Responsive Card Grid/CardGrid.css, Build a Responsive Card Grid/CardGrid.html
**Issue**
Closes #134 
**Resolution**
Built a responsive card grid layout using HTML and CSS.
**Changes Made**
Created two files, one HTML and one CSS files under a subdirectory of root directory.
**Screenshots**
=> Feature Added: #134 - responsive card grid layout

Python/count_number_of_words.py
Fixes #31 
Created a new file in "Python\count_number_of_words.py". Which will count words in a given text.
=> Program that count words in a text

Image Carousel/index.html, Image Carousel/script.js, Image Carousel/styles.css
Hey, i have add the basic images carousel code.If there is any changes then let me know.
Ticket #138
=> Added Image Carousel 

Simple Calculator/index.html, Simple Calculator/script.js, Simple Calculator/style.css
=> Built a Simple Calculator

Python/calculate_BMI.py
Fixes #34 
Created a new file in "Python\calculate_BMI.py" which will calculate BMI.
=> Added BMI calculator

Dropdown Menu Page/index.html
=> Added dropdown menu example page

Progress Bar/index.html, Progress Bar/script.js, Progress Bar/style.css
=> add progress bar

Character Occurences/count_char_occurences.java
Issue #50 I've added a Java program to count the occurrences of a character in a text.
=> Program to count occurences of character is added.

Form Validation/index.html, Form Validation/script.js, Form Validation/style.css
=> Basic Form Validation 

responsive nav bar/nav.css, responsive nav bar/nav.html, responsive nav bar/nav.js
I have added the responsive nav bar in a separate folder.
=> added the nav bar

Python/isArmstrong.py
Code to check whether a number is Armstrong number or not
=> Added isArmstrong.py

Python/L2_regularization_Implementation_from_scratch.py
Hey! @simranlotey , 
Here is the implementation of  Ridge Regression from Scratch.
A Python implementation of Ridge Regression, a linear regression technique with L2 regularization, built from the ground up using NumPy. Ridge Regression is a valuable tool for handling multicollinearity and preventing overfitting in linear regression models.
- **Ridge Regression Model**: This repository provides a `RidgeRegression` class that can be used for linear regression with L2 regularization.
- **Closed-Form Solution**: The implementation uses the closed-form solution for Ridge Regression to find the optimal coefficients.
=> Create  L2_regularization_Implementation_from_scratch.py

Python/removeDuplicate.py
Added code for removing all duplicates from a given string in Python
=> Added removeDuplicate.py

C++/BinarySearch.cpp, C++/two_array_equal_or_not.cpp
Issue no #187 
pls review and let me know @simranlotey
=> added binary search code

sorting_strings_array.ts
Regarding issue #181.
Added a TypeScript function that takes an array of strings and returns a new array with the strings sorted in alphabetical order.
=> Add TS function to sort an array of strings alphabetically

Event/very basic event system.ts
=> Added basic event handling 

Python/tree-sort.py
The tree sort algorithm has been added which sorts using in-order traversal.
=> Add Tree sort algorithm

Python/pong game.py
I have added **Pong Game** for this repository.
**Key Bindings :**
**1st Player** - "W" to move Up
"S" to move Down
**2nd Player** - "Up Arrow" to move up
"Down Arrorw" to move Down
there's an easter egg too :)
=> The Pong Game

C/cliCalculator.c, C/rockPaperScissorsGame.c
Created a C folder consisting two source files [ rockPaperScissors.c , cliCalculator.c ]
=> Added Some C programs

MatrixMultiplication.ts, SecondSmallestNumber.ts, SudokuSolver.ts
fix #176 
Please mark under hacktoberfest-accepted
=> Added SudokuSolver.ts

MatrixMultiplication.ts, SecondSmallestNumber.ts
Fixes issue #172 , #173
Please mark under Hacktoberfest-accepted
=> Created SecondSmallestNumber.ts and MatrixMultiplication.ts

BinarySearchWithQuickSort.ts, MatrixMultiplication.ts, SecondSmallestNumber.ts
fix #175 
Please mark under Hacktoberfest-accepted
=> Created BinarySearchWithQuickSort.ts

TypeScript_Searching_and_Sorting .ts
Solves Issue #175 
This code includes a binarySearch function for finding a target value in a sorted array and a quickSort function for sorting an array of numbers using the quicksort algorithm.
=> Typescript Binary Search and Quick Sort Added #175

cryptoGraphicHash.ts
Created a function which convert the given string to SHA-256 hash code
=> function to convet string to hash

Shell Script/fizzBuzz/fizzBuzz.sh, Shell Script/pwdgen.sh
under shell script file, created fizzBuzz.sh and pwdgen.sh .
"pwdgen.sh"  -> password generator
=> [FEATURE]: password generator and fizzBuzz in shell scripts

java/fizzbuzz/FizzBuzz.java
=> Create a Java FizzBuzz script

FizzBuzz/FizzBuzz.c
created a directory FizzBuzz and added FizzBuzz in C
=> Added FizzBuzz in C

FizzBuzz/FizzBuzz.cpp, FizzBuzz/FizzBuzz.ts
What does this PR do?
FizzBuzz.ts and FizzBuzz.cpp program files have been added in FizzBuzz directory
related to #225
=> Added FizzBuzz.ts and FizzBuzz.cpp

Shell Script/check_FilePermission.sh, Shell Script/copyFile.sh, Shell Script/dbBackup.sh, Shell Script/dirSize.sh, Shell Script/systemMonitoring.sh
Added some shell script program to resolve #207
=> Shell script program #207

Stop Watch/index.html, Stop Watch/script.js, Stop Watch/style.css
=> made webpage stopwatch

java/stockbuyproblem.java
Added program for Stock buy problem in java
=>  Stock buy problem 

Simple Quote Generator/index.html, Simple Quote Generator/script.js, Simple Quote Generator/style.css
What does this PR do?
Created directory Simple Quote Generator which includes index.html, style.css and script.js for simple quote generator application
related to #255
=> Created Simple Quote Generator

C/DDA.c
This is a DDA graphics algorithm.
Output:
=> Added DDA Algorithm

java/Todolist.java
This Java program is a task manager application with a user-friendly graphical interface. It allows users to create, track, and complete tasks efficiently. Users can add new tasks, mark them as done, and easily remove completed tasks. It provides a visual and interactive way to stay organized and manage daily tasks.
=> Added Todolist.java

Different-Time-Zones/index.html, Different-Time-Zones/script.js, Different-Time-Zones/style.html
=> Different-Time-Zones

java/ButterflyPattern.java
I have added Butterfly Pattern Program in Java language.
=> Butterfly Pattern Program in Java

java/NQueens.java
Heyy @simranlotey this is a very famous leetcode HARD problem - N-Queens
link - https://leetcode.com/problems/n-queens
Kindly merge my pull request as a part of Hactoberfest2023.
Thanks
=> Java code for N-Queens problem (Leetcode HARD)

C++/defang ip address.c
Solved Leetcode problem of defanging ip address. Clean code.
=> Created Defang ip address

CONTRIBUTING.md
#277 issue is solved. Please review this and merge it.
=> feat: add contributing file

Python/tic-tac-toe.py
hi @simranlotey,
This pull request introduces a simple graphical user interface (GUI) for a classic Tic Tac Toe game in Python using the Tkinter library. Players can interact with the GUI to place X's and O's on the board, and the game detects wins and draws. The code is structured in an organized manner to ensure readability and maintainability.
Please review and consider merging this pull request. Additionally, I kindly request the addition of the Hacktoberfest and Hacktoberfest-Accepted labels to this pull request.
Thank you!
@akashchaudhary-git
=> Added Python Tic Tac Toe gui game

CODE_OF_CONDUCT.md, CONTRIBUTING.md
#283 issue is solved. Please review this @simranlotey and merge it.
=> feat: add a code of conduct

simplePasswordGenerator.py
In this update, I've added a new Python script, **simplePasswordGenerator.py,** to the project in the "my-branch" branch of the repository. This script is designed to generate random passwords, providing a useful utility for users who need strong and secure passwords for various purposes.
The need for a simple password generator arises from the increasing importance of cybersecurity. In today's digital age, it's crucial to have strong, unique passwords for different online accounts to protect sensitive information from unauthorized access and cyber threats. Passwords generated by this script will include a mix of uppercase and lowercase letters, numbers, and special characters, making them resilient against common password attacks.
By adding this script to the project, we empower users …
=> Added Simple Password Generator

Python/0-1-Knapsack.py
- Added well documented python code for 0-1 Knapsack Problem.
- Clear and beginner friendly code
- This pr is for hacktoberfest, kindly merge is everything's alright
=> Added code for 0-1 Knapsack problem

sudokuSolver.py
=> Sudoku solver

Snake Game/snake.css, Snake Game/snake.html, Snake Game/snake.js
PR #303 
I have added a simple snake game as requested please assign this issue to me and merge my request.
=> Snake Game

guess-the-number-game/index.html, guess-the-number-game/script.js, guess-the-number-game/styles.css
Created guess-the-number game using HTML,CSS, and javascript
=> guess-the-number game is created

Memory/app.js, Memory/index.html, Memory/style.css
Simple Memory Game.  You have to find matching Colors
**Ideas for further improvements**
- Restart/Play Again Button
- Chose other Memory Symbols/Pictures
- Fancy Animation like flying Bats in the background 
- Animation for finding a Match
- A beatiful Alert Message or Event for winning the game
=> create memory game with colors

java/OrderAgnosticBinarySearch.java
Contribution for hacktoberfest 2023
=> Added an order agnostic binary search java program

Python/hangmanGame/hangman.py
using python, a basic hangman game was created.
=> [FEATURE]: hangman game created in python

Python/Typing_Game/README.md, Python/Typing_Game/typing.py
Closes issue #331 
I have created the Python Typing Game as per the specifications mentioned in issue #331. The game is functional, allowing users to practice and improve their typing skills. It is built using Python and provides an interactive typing experience.
=> feat: Create a speed typing test game using python

.github/workflows/main.yml
just add 'PERSONAL_ACCESS_TOKEN' in github env and then run workflow.
=> Created github actions for auto pull from upstream (main) users profile and merge to our forked repo in 11:55 pm  

C/goldbach_conjecture.c
added a simple goldbach conjecture program in c.
=> added a goldbach conjectture C program

Python/prime numbers.py
=> prime number

C/mergesort.c
Hello Sir,
I have created a simple merge sort program in C as my contribution to Hacktoberfest 2024. This is my first contribution as an open-source contributor. I kindly request your approval, as I learned Git and GitHub to make this contribution. I would be thrilled if you could label my submission with "Hacktoberfest Accepted," "Hacktoberfest 2024," "Hacktoberfest," and "Good Learner."
Thank you!
=>  Merge Sort in C

.vscode/settings.json, C++/House Robber.cpp, C++/Intersection of Two Arrays II.cpp, C++/Longest Common Prefix.cpp, C++/Majority Element.cpp, C++/Middle of the Linked List.cpp
This PR introduces C++ implementations for five commonly asked algorithmic problems. Each problem is solved using an efficient approach with well-structured code. #356
=> Add solutions for 5 standard algorithmic problems

C++/insertionsort.cpp, C++/mergesort.cpp
I have added the code for mergesort and insertion sort in cpp.
=> Fixed issue #353 merge sort and #issue352 quick sort addition

lorem_ipsum_generator/README.md, lorem_ipsum_generator/index.html, lorem_ipsum_generator/script.js, lorem_ipsum_generator/style.css
=> Added lorem-ipsum-generator with a README

Python/Tetris/tetris.py
This is a Tetris game made in python
Using these libraries 🎉
- pygame
- random
ScreenShot
Please accept my PR for Hacktoberfest ✅
=> Added Tetris Game in Python

C++/Stack_using_two_Queues.cpp
Added Stack using two queues program in C++ folder as a part of HacktoberFest.
=> Added Stack using two Queues program

.gitmodules
Added My Project into the repo
=> Added Thala-Calculator as a submodule

DakrModeToggle/index.html, DakrModeToggle/script.js, DakrModeToggle/styles.css
Basic Web dev feature of dark mode toggle is made using html css js
=> Dark Mode Feature added

C++/valid_paranthesis_problem.cpp
added valid paranthesis problem
=> added valid paranthesis problem

.vscode/settings.json, C/binarysearch.c, C/linearsearch.c
I have added the binary search and linear search algorithms in C language.
fixed issue #392
=> Searching Algorithms in C

Python/continent_quiz.py
Added a continent quiz for 5 different countries.
=> Added continent_quiz.py

Python/two-sum.py
I have added a simple Two Sum Leetcode problem in python folder.
=> add: adds Two sum python problem

PHP/CarsListPanel/Add.php, PHP/CarsListPanel/Delete.php, PHP/CarsListPanel/Logout.php, PHP/CarsListPanel/Update.php, PHP/CarsListPanel/View.php, PHP/CarsListPanel/aa-error-check.php, PHP/CarsListPanel/index.php, PHP/CarsListPanel/login.php, PHP/CarsListPanel/pdo.php, PHP/MathBasicOperations/index.php
Hi! I have developed a simple basic calculator using PHP.
=> Created a simple calculator with basic mathematical operations

C++/postfix-evaluation.cpp
**Problem Statement:**
Write a C++ program to evaluate a postfix expression using a stack. The expression consists of single-digit operands and operators (+, -, *, /).
Algorithm used:
1. initialize stack to store operands
2. scan the expression from left to right and do the following for every element
3. if the element is an operand, push it into the stack
4. if the element is an operator, pop two operands from the stack and apply the operator, push the result back into the stack
5. when the expression is ended, the number in the stack is the final result
=> Added Postfix expression evaluation using stack

Chat_with_pdf/Gemini_ChatMultipdf.ipynb
I completed my project chat with pdf, which gives efficient results.
=> Added my project chat with pdf using gemini

Python/3d_pose_estimation/3d_pose_estimation.py, Python/3d_pose_estimation/README.md
This 3D Pose estimation has been done using mdeiapipe's soltions.pose library. It is capable of detecting 33 key landmark points in bith 2d as well as 3d. I have used 3d coordinates, where every frame in the video is processed and passed on to the model.
=> Added 3d pose estimation

Command-Line Quiz Application/questions.json, Command-Line Quiz Application/quiz_app.py
The Command-Line Quiz Application is an interactive tool designed to enhance knowledge across various subjects through engaging quizzes. Built for enthusiasts looking to challenge their understanding of topics such as History, Geography, Science, and Arts.
=> Command-line-Quiz-App

java/Matrix_Multiplication.java
This Java program multiplies two matrices by first taking their dimensions and elements as input from the user. It checks if the multiplication is feasible based on matrix dimensions, performs the multiplication using nested loops, and then outputs the resultant matrix.
=>  Add matrix multiplication in Java

java/String_atoi.java
This code implements a custom atoi`function that converts a string to an integer, handling optional leading spaces, a sign (+ or -), and ensuring the result stays within Java’s integer limits. It parses each character, accumulates digits to form the integer, and returns the result with overflow protection.
=> Add String to Integer(atoi) in Java

C++/540. Single Element in a Sorted Array.cpp
Question
You are given a sorted array consisting of only integers where every element appears exactly twice, 
except for one element which appears exactly once.
Return the single element that appears only once.
(Your solution must run in O(log n) time and O(1) space.) 
Example 1:
Input: nums = [1,1,2,3,3,4,4,8,8]
Output: 2
Example 2:
Input: nums = [3,3,7,7,10,11,11]
Output: 10
Constraints:
1 <= nums.length <= 105
0 <= nums[i] <= 105
Hi , @simranlotey can you please assign the hacktoberfest tag , 
Thank you
=> adding q.no 540 - single element in sorted array

C++/height.cpp, C++/insertion-sort.cpp
=> insertion sort

C++/HollowDiamond.cpp
Pattern for Hollow Diamond in C++
issue fixes #379
=> Hollow Diamond in C++

java/HollowDiamond.java
Pattern for Hollow Diamond in Java
issue fixes #379
=> Hollow Diamond in java

C++/QuickSort.cpp, C++/radixSort.cpp, C++/selectionSort.cpp
=> added radix sort, quick sort and selection sort
